# Generated by Django 4.0.1 on 2022-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_blog_deleted_blog_posts_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_posts_total',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='deleted_blog_posts_total',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(verbose_name='Текст публикации'),
        ),
    ]
