# Generated by Django 4.0.1 on 2022-01-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_blogpost_options_remove_blog_blog_posts_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='delete_date',
            field=models.DateTimeField(null=True, verbose_name='Время удаления'),
        ),
    ]
