# Generated by Django 4.0.1 on 2022-01-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_blogpost_options_blogpost_delete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_deleted',
        ),
    ]
