# Generated by Django 4.0.1 on 2022-01-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_remove_blogpost_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='delete_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата удаления'),
        ),
    ]
